version: '3.7'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    volumes:
      - ./data:/data
    ports:
      - 2181:2181

  kafka9092:
    image: wurstmeister/kafka
    ports:
      - 9092:9092
    environment:
      KAFKA_BROKER_ID: 0
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://192.168.99.1:9092
      KAFKA_CREATE_TOPICS: "Link-kafka:1:0"   #kafka启动后初始化一个有2个partition(分区)0个副本名叫Link-kafka的topic
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_LISTENERS: PLAINTEXT://192.168.99.1:9092
    volumes:
      - ./kafka-logs:/kafka
    depends_on:
      - zookeeper