server:
  port: 9090
  servlet:
    context-path: /demo

spring:
  dubbo:
    application:
      name: springboot-dubbo-provider
      registry: zookeeper://127.0.0.1:2181
#      registry: zookeeper://ip地址:2181